# Generated by Django 4.0.2 on 2022-02-23 11:01

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(default=False, max_length=13)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_number', models.CharField(max_length=20)),
                ('file_number', models.CharField(max_length=20)),
                ('initiation_date', models.DateTimeField(verbose_name='Date initiated')),
                ('next_appointment', models.DateTimeField(verbose_name='Next appointment')),
                ('cpt', models.CharField(max_length=10)),
                ('date_of_enrollment', models.DateTimeField(auto_now=True, verbose_name='Date of Enrollment')),
                ('visit_date', models.DateTimeField(auto_now=True, verbose_name='Visit Date')),
            ],
        ),
        migrations.CreateModel(
            name='DispensationFillable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='amount')),
            ],
        ),
        migrations.CreateModel(
            name='DrugFillable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ViralLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_date', models.DateTimeField(verbose_name='viral load date')),
                ('result', models.CharField(max_length=20)),
                ('remark', models.TextField(max_length=64)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.clinic')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.regimen')),
            ],
        ),
        migrations.CreateModel(
            name='SupportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.actor')),
            ],
        ),
        migrations.CreateModel(
            name='DrugDispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_date', models.DateTimeField(verbose_name='Drug dispensation date')),
                ('fillables', models.ManyToManyField(through='ncapp.DispensationFillable', to='ncapp.DrugFillable')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.nurse')),
            ],
        ),
        migrations.AddField(
            model_name='dispensationfillable',
            name='dispensation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.drugdispensation'),
        ),
        migrations.AddField(
            model_name='dispensationfillable',
            name='fillable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.drugfillable'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.nurse'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.patient'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.site'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='support_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.supportgroup'),
        ),
        migrations.AddField(
            model_name='actor',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.location'),
        ),
    ]
