# Generated by Django 4.0.2 on 2022-02-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0002_supportgroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=20)),
                ('wt', models.FloatField(max_length=1000, verbose_name='Weight')),
                ('ht', models.IntegerField(verbose_name='Height')),
                ('sbp_dbp', models.CharField(max_length=20, verbose_name='Sytolic blood pressure over Dystolic blood pressure')),
                ('side_effect', models.CharField(choices=[('NO', 'NO'), ('PN', 'PN'), ('HP', 'HP'), ('SK', 'SK'), ('LIP', 'LIP'), ('OTH', 'OTH')], max_length=3, verbose_name='Side effect')),
                ('tb_status', models.CharField(choices=[('No TB', 'NO TB'), ('Y', 'Yes'), ('C', 'conclusive'), ('on_RX', 'On RX')], max_length=20, verbose_name='TB Status')),
                ('Vl', models.CharField(max_length=20, verbose_name='Viral load')),
                ('dose_missed', models.IntegerField()),
                ('pill_count', models.IntegerField()),
                ('number_of_regimen_pills', models.IntegerField()),
                ('cpt', models.IntegerField()),
                ('pyridoxine', models.IntegerField()),
                ('inh', models.IntegerField()),
                ('bp_drug', models.CharField(max_length=20)),
                ('number_of_tabs', models.IntegerField()),
                ('fp_meth', models.IntegerField()),
                ('number_of_condoms', models.IntegerField()),
                ('adverse_outcome', models.CharField(max_length=20)),
                ('art_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.regimen')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.patient')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.site')),
                ('support_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.supportgroup')),
            ],
        ),
    ]
