# Generated by Django 4.0.2 on 2022-02-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0003_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='visit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Visit Date'),
        ),
    ]
