# Generated by Django 4.0.2 on 2022-02-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0004_art_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='Vl',
        ),
        migrations.RemoveField(
            model_name='art',
            name='cpt',
        ),
        migrations.RemoveField(
            model_name='art',
            name='file_number',
        ),
        migrations.RemoveField(
            model_name='art',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='art',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='art',
            name='site',
        ),
        migrations.RemoveField(
            model_name='art',
            name='support_group',
        ),
        migrations.RemoveField(
            model_name='art',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='art',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ncapp.clinic'),
            preserve_default=False,
        ),
    ]
