# Generated by Django 4.0.2 on 2022-02-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0005_remove_art_vl_remove_art_cpt_remove_art_file_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='date_of_enrollment',
            field=models.DateTimeField(verbose_name='Date of Enrollment'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='visit_date',
            field=models.DateTimeField(verbose_name='Visit Date'),
        ),
    ]
