# Generated by Django 4.0.2 on 2022-02-28 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0006_alter_clinic_date_of_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ncapp.clinic'),
        ),
    ]
