# Generated by Django 3.2.12 on 2022-03-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0009_widget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugdispensation',
            name='fillables',
        ),
        migrations.AlterField(
            model_name='dispensationfillable',
            name='dispensation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ncapp.drugdispensation'),
        ),
        migrations.AlterField(
            model_name='dispensationfillable',
            name='fillable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ncapp.drugfillable'),
        ),
    ]
