# Generated by Django 3.2.12 on 2022-03-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0011_alter_nurse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensationfillable',
            name='dispensation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.drugdispensation'),
        ),
        migrations.AlterField(
            model_name='dispensationfillable',
            name='fillable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.drugfillable'),
        ),
    ]
