# Generated by Django 3.2.12 on 2022-03-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0012_auto_20220303_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugdispensation',
            name='drugs',
            field=models.ManyToManyField(through='ncapp.DispensationFillable', to='ncapp.DrugFillable'),
        ),
    ]
