# Generated by Django 3.2.12 on 2022-03-14 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0013_drugdispensation_drugs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name': 'ART Dispensation'},
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'Appointment'},
        ),
        migrations.AlterModelOptions(
            name='dispensationfillable',
            options={'verbose_name': 'Drug Dispensation'},
        ),
        migrations.AlterModelOptions(
            name='drugdispensation',
            options={'verbose_name': 'Dispensation session'},
        ),
        migrations.AlterModelOptions(
            name='drugfillable',
            options={'verbose_name': 'Drug'},
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
        ),
    ]
