# Generated by Django 3.2.12 on 2022-04-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0016_auto_20220322_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ncapp.clinic', verbose_name='Visit'),
        ),
        migrations.AlterField(
            model_name='art',
            name='fp_meth',
            field=models.CharField(max_length=20),
        ),
    ]
