# Generated by Django 3.2.12 on 2022-04-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0017_auto_20220406_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='date_of_enrollment',
            field=models.DateField(verbose_name='Date of Enrollment'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='initiation_date',
            field=models.DateField(verbose_name='Date initiated'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='next_appointment',
            field=models.DateField(verbose_name='Next appointment'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='viralload',
            name='remark',
            field=models.TextField(default='', max_length=64),
        ),
    ]
