# Generated by Django 3.2.12 on 2022-04-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0019_auto_20220411_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='support_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ncapp.supportgroup'),
        ),
    ]
