# Generated by Django 3.2.13 on 2022-04-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0020_patient_support_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Drug amount')),
                ('datet', models.DateField(verbose_name='Date of Stock')),
                ('fillable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.drugfillable', verbose_name='Drug')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncapp.nurse')),
            ],
            options={
                'verbose_name': 'Drug Stock',
            },
        ),
    ]
