# Generated by Django 3.2.13 on 2022-04-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncapp', '0022_rename_datet_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='support_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ncapp.supportgroup'),
        ),
    ]
